orb.yml

PTAL @hootener 
For users that aren't using the `flags` feature, the bash uploader is trying to parse `-f` as a flag.  This is messing with the rest of the arguments.  By moving it to the end, we avoid that issue, but the bash uploader will eventually need to be updated

Move flags flag to end of bash command to avoid conflict

---

.gitignore
package-lock.json
package.json

Bump to 1.1.1 due to security vulnerability on `lodash`
https://github.com/advisories/GHSA-p6mc-m468-83gw

[semver:patch] Bump to 1.1.1

---

.circleci/config.yml

Expects `CIRCLE_TOKEN`, but that's not the name

Use ORB_PUBLISH_TOKEN

---

src/orb.yml

I think this change causes bash command error.
https://github.com/codecov/codecov-circleci-orb/pull/57/files#diff-73bdc7f6ecdb2576f0a66a84f59829dbacbad92b6a46ffe50374f8707139fdb1R45
I forked your repo and fixed it, please accept this if it is OK.

Fixed bash command failure due to unescaped line break

---

src/@orb.yml

This is a copy of https://github.com/codecov/codecov-circleci-orb/pull/70
Unfortunately, this doesn't give @kpurdon all the credit he deserves, but getting this out is a higher priority. We will explore why forks are unable to publish dev versions.
This PR adds bash checksum validation before uploading.

Add validation of checksums

---

CHANGELOG.md
package-lock.json
package.json
src/@orb.yml

Removes the need for `VERSION` and pegs to `production`
fixes https://github.com/codecov/codecov-circleci-orb/issues/77#issuecomment-820912091

[semver:patch] Update validation regex and add shasum flexibility

---

CHANGELOG.md
README.md
package.json
src/@orb.yml

Update the bash script download with best practices

[semver:patch] Update bash curling best practices and bump to 1.1.6

---

.circleci/config.yml
CHANGELOG.md
README.md
package-lock.json
package.json
src/@orb.yml

This PR adds support for Windows builds. It introduces the `using_windows` flag that must be set to `true` in order to properly validate the bash script with Powershell commands.
Fixes https://github.com/codecov/codecov-circleci-orb/issues/83

[semver:patch] Add support for Windows builds

---

CHANGELOG.md
README.md
package.json
src/@orb.yml

Using the given params expects a password for user `tfile`. This should not be necessary.

[semver:patch] Fix issue with Windows curling the bash script

---

.circleci/config.yml
CHANGELOG.md
README.md
package-lock.json
package.json
src/@orb.yml

Uses the sha{x} commands as further backups to systems that do not have `shasum`, namely Windows `bash.exe`

[semver:patch] Include sha{x}sum commands for windows bash

---

src/@orb.yml

Supercedes https://github.com/codecov/codecov-circleci-orb/pull/93 due to permissions issue

[semver:patch] chore: switch to using env_var_name for token type

---

.circleci/config.yml
CHANGELOG.md
README.md
package-lock.json
package.json
src/@orb.yml

This allows for specifying `version` as part of the orb. Users can upload using that version of the Codecov uploader. It defaults to `latest`.

[semver:minor] Allow specifying version of Codecov uploader

---

CHANGELOG.md
README.md
src/@orb.yml

Context: https://github.com/codecov/uploader/issues/475

[semver:patch] unset NODE_OPTIONS to prevent exit 4

---

.circleci/config.yml
README.md
src/@orb.yml

This change explicitly defines the bash shell on the run steps in the orb.
Why? On Windows, the default executor shell is PowerShell, which means if someone uses this orb without overriding the default shell the orb commands will fail to run because they will attempt to run in PowerShell.

Explicitly specify bash shell on run steps

---

.circleci/config.yml
README.md
src/@orb.yml

Reverts codecov/codecov-circleci-orb#125
This will break on `alpine` builds

Revert "Explicitly specify bash shell on run steps"

---

CHANGELOG.md
package-lock.json
package.json

**Fixes**
- #105: Bump path-parse from 1.0.6 to 1.0.7
- #126: Bump dependencies
- #127: fix(ci): install Git
- #130: Bump dependencies
- #132: Disabling auto update on brew install
- #135: ci: bump deps

release: bump to 3.2.3

---

.circleci/config.yml
.circleci/test-deploy.yml
README.md
src/scripts/download.sh
src/scripts/upload.sh
src/scripts/validate.sh

fixes https://github.com/codecov/codecov-circleci-orb/issues/148

fix: prefix codecov to bash vars

---

.circleci/test-deploy.yml
src/commands/upload.yml
src/scripts/upload.sh

This PR fixes the ${CIRCLE_BUILD_NUM} bug in the upload name.
This PR allows users to specify environment variables that specify the
flags to be used in the uploader.
Fixes: https://github.com/codecov/platform-team/issues/83

Fix CIRCLE_BUILD_NUM bug and allows users to specify env vars as flags

---

.circleci/test-deploy.yml
src/commands/upload.yml
src/scripts/download.sh
src/scripts/upload.sh
src/scripts/validate.sh

This PR adds the cli as the uploader 
notes to reviewer:
- I'm not sure if I should change the public pgp key, is it for the uploader or is it for codecov in general? 
- I've tested the upload.sh script but couldn't test the validate or the download. Please let me know if there's a way we can test it

using codecovcli as the uploader

---

.circleci/test-deploy.yml
package-lock.json
package.json
src/examples/basic_upload.yml
src/examples/node_test_upload.yml
src/scripts/upload.sh

fixes https://github.com/codecov/feedback/issues/246

fix: test without flags

---

src/commands/upload.yml

The options available on the codecov CLI are `coverage` and `test_results`, so I believe that should be mirrored here.

Update report_type docstring
